### ISSUE TITLE
Hack teleporting from top of the map to bottom

### ISSUE THREAD

**Issue by SomeoneCares11** [Megabyte918/MultiOgar-Edited#1408]
Hi, i got hack today, he is teleport from top of the map to bottom
flying to top 2 and eating him!

how i prevent this hackers from doing so.
i didn't got such of hackers in 1.5.0, i don't know is this hacker new or designed to the new version.

my current version 1.6.1

**Comment by AlexHGaming** [comment]
@SomeoneCares11 send a GIF / video clip of such thing happening.

**Comment by OfficialKake** [comment]
This script i modified works on agar.red
`
var EjectDown = false;
var speed = 1;
window['addEventListener']('keydown', keydown);
window['addEventListener']('keyup', keyup);
var Feed = false;
var Speed = 25; //uknow

function split() {
    var EjectDown = false;
    var speed = 1;
    $('body')['trigger']($.Event('keydown', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }));
    $('body')['trigger']($.Event('keyup', {
        keyCode: 32
    }))
}

function mass() {
    if (Feed) {
        window['onkeydown']({
            keyCode: 87
        });
        window['onkeyup']({
            keyCode: 87
        });
        setTimeout(mass, Speed)
    }
}

function keydown(_0xdd63x8) {
    if (_0xdd63x8['keyCode'] == 69) {
        Feed = true;
        setTimeout(mass, Speed)
    };
    if (_0xdd63x8['keyCode'] == 75) {
        X = window['innerWidth'] / 5;
        Y = window['innerHeight'] / 0;
        $('canvas')['trigger']($.Event('mousemove', {
            clientX: X,
            clientY: Y
        }))
    };
    if (_0xdd63x8['keyCode'] == 16 || _0xdd63x8['keyCode'] == 52) {
        split();
        setTimeout(split, Speed);
        setTimeout(split, Speed * 2);
        setTimeout(split, Speed * 3)
    };
    //if (_0xdd63x8['keyCode'] == 82 || _0xdd63x8['keyCode'] == 'yourkey') {
        //split();
        //setTimeout(split, Speed);
        //setTimeout(split, Speed * 2)
    //};
    if (_0xdd63x8['keyCode'] == 81 || _0xdd63x8['keyCode'] == 'yourkey') {
        split();
        setTimeout(split, Speed)
    };
    if (_0xdd63x8['keyCode'] == 'yourkey' || _0xdd63x8['keyCode'] == 'yourkey2') {
        split();
        split(1000);
        setTimeout(split, Speed);
        setTimeout(split, Speed * 2);
        setTimeout(split, Speed * 4)
    };
    if (_0xdd63x8['keyCode'] == 76) {
        X = window['innerWidth'] / 0;
        Y = window['innerHeight'] / 5;
        $('canvas')['trigger']($.Event('mousemove', {
            clientX: X,
            clientY: Y
        }))
    };
    if (_0xdd63x8['keyCode'] == 74) {
        X = window['innerWidth'] / -0;
        Y = window['innerHeight'] / 3.2;
        $('canvas')['trigger']($.Event('mousemove', {
            clientX: X,
            clientY: Y
        }))
    };
    if (_0xdd63x8['keyCode'] == 73) {
        X = window['innerWidth'] / 3.0;
        Y = window['innerHeight'] / -0;
        $('canvas')['trigger']($.Event('mousemove', {
            clientX: X,
            clientY: Y
        }))
    }
}

function keyup(_0xdd63x8) {
    if (_0xdd63x8['keyCode'] == 69) {
        Feed = false
    }
}
if (event['keyCode'] == 68) {
    X = window['innerWidth'] / 0;
    Y = window['innerHeight'] / 5;
    $('canvas')['trigger']($.Event('mousemove', {
        clientX: X,
        clientY: Y
    }))
}
`

**Comment by SomeoneCares11** [comment]
@AlexHGaming see @OfficialKake reply, thats what is going on in my servers too.

@OfficialKake does it works with 1.5.0 ? Or you didn't try yet? and what is the solution in your opinion

**Comment by Luka967** [comment]
Definitely the same issue as #1370 has, but now that it's been reported again this looks like our issue. I'll look into it in about 12ish hours

**Comment by OfficialKake** [comment]
@SomeoneCares11 I dont try for 1.5.0

**Comment by MastaCoder** [comment]
Didn't read the other issue, but it appears Luka already did some tests and it doesn't work with the latest version of the server. Can we get more people to do tests with newer versions of the server see if it still occurs at all or if it's just these two running custom versions of MultiOgar?

**Comment by OfficialKake** [comment]
@MastaCoder I can help

**Comment by OfficialKake** [comment]
I haved tested on 6 servers:
MultiOgar
1.2.68 = Does not work.

MultiOgar-Edited
1.3.5 = Does not work.
1.4.2 = Does not work.
1.6.0 = Works.
1.6.1 = Works.

MultiOgar-Edited-Unlimited
1.0.3 = Does not work.

**Comment by Luka967** [comment]
Good work on testing them all, I'll get a patch up ASAP

**Comment by Agarian** [comment]
@OfficialKake version 1.5.0 is here: https://github.com/Megabyte918/MultiOgar-Edited/tree/8eec70e43dc9ab9a891a5163a23f01d38abb07e0.

**Comment by SomeoneCares11** [comment]
Any news?

**Comment by OfficialKake** [comment]
@Agarian Thanks.

**Comment by AlexHGaming** [comment]
This has been fixed.
Close.

**Comment by SomeoneCares11** [comment]
Please don't close, i'm still having this issue, even after the fix. i'm trying to inform you with more details.

**Comment by SomeoneCares11** [comment]
https://youtu.be/hoBdl2cfgbQ ,This is after the fix.

**Comment by MastaCoder** [comment]
Now?
