### ISSUE TITLE
Auto Restart Bug

### ISSUE THREAD

**Issue by fayizan** [Megabyte918/MultiOgar-Edited#1435]
After Auto Restart, Server Bots doesn't get added back and bug cause players to spectate the whole server like this 
![screenshot_145](https://user-images.githubusercontent.com/19163419/36945993-f9833e3c-1fdb-11e8-8d7a-c8006822fcfd.png)

**Comment by AlexHGaming** [comment]
Duplicated.

**Comment by Agarian** [comment]
I'm pretty sure I fixed the bots bug a long time ago...

**Comment by fayizan** [comment]
@Agarian I tried out with the latest version and the bug still exist...
@AlexHGaming I cant find the duplicate :|

**Comment by fayizan** [comment]
@Agarian @Megabyte918 heilp

**Comment by Agarian** [comment]
I'm sorry, I can't duplicate it...
