### ISSUE TITLE
connection hangs after while

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#406]
After around 10 minuetes no-one can connect to the server you just get the welcome message and then "Connecting..." flashes.

**Comment by AlexHGaming** [comment]
Are you using Codeanywhere?

**Comment by Niall7459** [comment]
What is Codeanywhere?

**Comment by Niall7459** [comment]
No but I have my servers behind an Nginx reverse proxy

**Comment by Megabyte918** [comment]
This does not happen with me. What are you using to host? Are there any errors in logs?

**Comment by Niall7459** [comment]
Ubuntu server I am running via console-plus.js

I can sometimes not connect back to the server here is image:
![ogar-error](https://cloud.githubusercontent.com/assets/9781846/21964517/4bb96794-db45-11e6-8f22-179a75afae1a.gif)

**Comment by Niall7459** [comment]
Maybe because all players have IP 127.0.0.1
I have set IP limit to 0 (disable)

**Comment by AlexHGaming** [comment]
It is probably your client.
Try it on the vanilla client.

**Comment by systemroot** [comment]
i don't think this is a problem with mg-edited, 
that isn't because of ip, i had the same problem when i was using my proxy way with nginx. but i didn't found from logs why :confused: 

Can you post your nginx rules? domain/proxy rules which are on /etc/nginx/sites-enabled ?!
and if is possible to post what is into nginx.conf

**Comment by Niall7459** [comment]
location /ncoms1501/ {

	rewrite ^/ncoms1501/(.*)$ /$1 break;
        deny 185.5.67.179;

	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
               proxy_http_version 1.1;
	proxy_pass http://127.0.0.1:1501;
	proxy_redirect off;	
	}

**Comment by Niall7459** [comment]
Client is Cigar

**Comment by MastaCoder** [comment]
Do you have client binding on?

**Comment by Niall7459** [comment]
clientBind =""

So im guessing no.

MultiOgar-Edited used to work this way...

**Comment by Niall7459** [comment]
I am not getting the problem with OgarServ that is on /ncoms1502/ It works perfectly.

**Comment by Niall7459** [comment]
I have mobilePhysics = 1 ???

Would not make difference?

**Comment by Niall7459** [comment]
Once I "exit" the server and reboot it works again for a bit.

**Comment by Niall7459** [comment]
It has happened again!

**Comment by Niall7459** [comment]
please please PLEEEEAAAASE!

**Comment by systemroot** [comment]
try to replace 
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $http_host;
           proxy_http_version 1.1;
proxy_pass http://127.0.0.1:1501;
proxy_redirect off;	
```

with 
```
            proxy_pass http://127.0.0.1:1501;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
```

and take a look into other rules maybe there is something which is limiting something!

**Comment by Niall7459** [comment]
@systemroot 

proxy_set_header Connection $connection_upgrade;

Error: unkown "connection_upgrade"

**Comment by systemroot** [comment]
open **nginx.conf**
and after **http {**
wrote this 
```
       log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                                '"$request" $status $body_bytes_sent '
                                '"$http_referer" "$http_user_agent"'
                                'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
```
like https://github.com/systemroot/my-nginx/blob/master/etc/nginx/nginx.conf#L12

then put logs maybe you can found what's the problem 
```
            access_log /home/access.log upstream_time;
            error_log /homeerror.log;
            proxy_pass http://127.0.0.1:1501;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
```

>Error: unkown "connection_upgrade"

what's your nginx version ?

**Comment by Niall7459** [comment]
I replaces $connection_upgrade with "upgrade"

**Comment by Niall7459** [comment]
nginx/1.10.0 (Ubuntu)

**Comment by Jhair2015** [comment]
@Megabyte918 That same happens to me, the players on my server can not join after about 10 minutes playing, I use DigitalOcean to host my server.

**Comment by Niall7459** [comment]
Yes it i around 10 mins until no one could connect.

**Comment by systemroot** [comment]
put those
```
deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx
deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx
```
into /etc/apt/source.list
then 
```
sudo apt-get update -y; sudo apt-get upgrade -y
sudo apt-get clean && sudo apt-get install nginx -y
service nginx restart
```
careful maybe this can delete your sites into /etc/nginx/sites-enabled , so make a copy of your vhosts

**Comment by Niall7459** [comment]
I can do this when I next have time

**Comment by Niall7459** [comment]
With new Nginx config.. uptime 12 mins and still working.

**Comment by systemroot** [comment]
nice to hear that..

**Comment by Niall7459** [comment]
13 mins still goin.

**Comment by Niall7459** [comment]
broken..

**Comment by Niall7459** [comment]
Same thing. flashing connecting dialog.

**Comment by systemroot** [comment]
did you put logs? if yes what the output of 
```
cat /home/error.log
```
?!

**Comment by Niall7459** [comment]
I forgot enble...

**Comment by Niall7459** [comment]
Will enable now

**Comment by systemroot** [comment]
ok try

**Comment by Niall7459** [comment]
I could not do the access_log because upstream_time want valid log but i have done the other.

going to wait until it breaks

**Comment by Niall7459** [comment]
did not mean to close

**Comment by Niall7459** [comment]
I have this in error.log, but I can still connect to the server:

2017/01/15 17:52:06 [error] 31438#31438: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 31.185.221.6, server: _, request: "GET /ncoms1501/ HTTP/1.1", upstream: "http://127.0.0.1:1501/ncoms1501/", host: "**.***.**.***"

IP has been replaced though for security.

**Comment by systemroot** [comment]
when no one can't connect read the latest log

**Comment by Niall7459** [comment]
No one can connect, No errors.

**Comment by systemroot** [comment]
try
```
            access_log /home/access.log upstream_time;
            error_log /home/error.log;
            proxy_pass http://127.0.0.1:1501;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout  36000s;
```

**Comment by Luka967** [comment]
If the problem persists, put a log file in a .ZIP and attach it on github. I'll look into it.

**Comment by Agarian** [comment]
I have a theory: it might have been when @Megabyte918 changed some `==` to `===`, and `!=` to `!==`, etc.
I noticed a certain bug, might just have been me, but when i tried to spectate when nobody was "alive", the game should have gone into freeroam mode on the spot, but it didn't. I changed one of the terms with `===` back to `==` (don't remember what), then freeroam activated just fine (still when nobody was "alive")

**Comment by systemroot** [comment]
@Agarian  this problem has nothing to do with multiogar-edited.
nginx drop connection with websocket if for 60s proxy doesn't transfer any package/s. 
so for that i add proxy timeout. 

you can read nginx wiki http://nginx.org/en/docs/http/websocket.html

**Comment by Megabyte918** [comment]
@Agarian Fixed

**Comment by Agarian** [comment]
That's the freeroam bug outta the way haha

**Comment by MSINIRI** [comment]
@Megabyte918 the problem still not fixed but no problems in old version 1.4.7 please try to fix that
Thanks ..

**Comment by Luka967** [comment]
@MSINIRI Update your server then

**Comment by MSINIRI** [comment]
@Luka967 But anti bots not added in old version

**Comment by Megabyte918** [comment]
The issue is not with anti-bot, nor is it with the server itself; It is either what you are using to host, or the client you are using. Because this problem has never happened to me or my friends, and I leave my server on overnight.

**Comment by fayizan** [comment]
Just updated to new version, got this error
![screenshot_35](https://cloud.githubusercontent.com/assets/19163419/22007642/51b619d4-dc9a-11e6-86b8-abdf633651c4.png)

**Comment by Megabyte918** [comment]
@fayizan Should be fixed

**Comment by fayizan** [comment]
@Megabyte918 still the server stop accepting connection after certain time bro

**Comment by Jhair2015** [comment]
@fayizan Same Problem @Megabyte918

**Comment by Megabyte918** [comment]
I don't know what the problem is.. I just left my server on overnight with myself on spectate and I came back the next morning and it was exactly how I left it (using a freshly downloaded version). Connections still worked from all clients, atleast the ones that I tried. Also anti-bot should not be the problem, if it was then players would not be able to connect at all, rather than after a certain amount of time.

**Comment by ARBCells** [comment]
@Megabyte918 I experience the same problems with our server. After a while (may vary between 10-30 minutes), the server is turning off and no one can connect and ''connecting'' starts flashing. This never happened before in the older versions,  so I think the problem is from MultiOgar-Edited 1.5 unfortunately.

I hosting the server on Windows Server 2012 R2 with the following stats:
Memory: 4 GB HDD: 40 GB Bandwith: 3 TB

Joseph

**Comment by Megabyte918** [comment]
@ARBCells What steps did you take to produce this bug? Are there any errors in your server logs?

**Comment by fayizan** [comment]
@Megabyte918 can I send you log files through skype..?

**Comment by ARBCells** [comment]
@Megabyte918 Please check your e-mail (the one you have entered on your profile). I sent you a message about my problem. I am very grateful.

Joseph

**Comment by Niall7459** [comment]
Confirmed, not ngunx problem, seems to happen on direct connections as well.

**Comment by ARBCells** [comment]
@Niall7459 Can u please contact me.

**Comment by duwayy** [comment]
Same problem under Ubuntu + apache

**Comment by markstoep** [comment]
Same problem here..

**Comment by Megabyte918** [comment]
Try using the GameServer.js and PlayerTracker.js files from this point in time: https://github.com/Megabyte918/MultiOgar-Edited/tree/7237c04122133e25ea32861ba9fb88f6e43c6509

Let me know if it keeps happening or not.

**Comment by ARBCells** [comment]
@Megabyte918 I think it works when the server has been up for 296 minutes atm BUT the problem now is that the cell does not allow you to get bigger than 10 mass. How do we solve this?

**Comment by ARBCells** [comment]
@Megabyte918 444 minutes and still going :) I think the connection issue are solved now. But pls give me a solution to the above noticed problem, the cell does not allow to grow more than 10 mass.

**Comment by Megabyte918** [comment]
Sorry for late response, have you edited your Cell.js by any chance? I would recommend using the latest one, the bug you are describing has been fixed a while ago.

**Comment by duwayy** [comment]
For me connection issue is fixed with old GameServer.js and PlayerTracker.js files, but I also face 10 mass cell issue and can not grow

**Comment by duwayy** [comment]
And I use latest cell.js

**Comment by mrzack506** [comment]
Same, still happening when multiple people join, @Megabyte918 thats why when you left the server on, it was fine.

**Comment by Megabyte918** [comment]
use the Cell.js from this branch: https://github.com/Megabyte918/MultiOgar-Edited/blob/Updates/src/entity/Cell.js

I cannot reproduce this problem

**Comment by ARBCells** [comment]
Here is the solution that fixed my connection problems :)

1. Download MultiOgar-Edited from this point of time: https://github.com/Megabyte918/MultiOgar-Edited/tree/7237c04122133e25ea32861ba9fb88f6e43c6509

2. Copy Playerhandler.js, UpdateLeaderboard.js and Chatmessage.js from the current edition and replace with the old files that you just downloaded :) 

My server has been up now for over one day with several players at same time without any errors.

/ ARB Cells

**Comment by ZfsrGhS953** [comment]
@ARBCells There's no PlayerHandler.js in MultiOgar-Edited, it only exists in Ogar.

**Comment by ARBCells** [comment]
@ZfsrGhS953 Opss... I meant, of course, the PacketHandler.js file :-)

**Comment by Luka967** [comment]
lol

**Comment by duwayy** [comment]
@ARBCells did it fix 10 mass bug ? Doing what you did and still have it...

**Comment by ARBCells** [comment]
@duwayy Yes It did :) Make sure u did all right :)

**Comment by Megabyte918** [comment]
This was fixed in the most recent pull request, I will merge the changes when its finished

**Comment by ARBCells** [comment]
@Megabyte918 Tell me when you merge it :)

**Comment by markstoep** [comment]
Can someone tell me which file the fix is for the 10 mass bug? Every update i try it's not fixing the bug.. Thanks!

**Comment by Megabyte918** [comment]
@markstoep use the latest updates from the "update" fork
