### ISSUE TITLE
Problem with LB on Other Protocol

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#599]
![image](https://cloud.githubusercontent.com/assets/18153674/23336206/341bd672-fb97-11e6-98fb-149857c6fb3c.png)
![image](https://cloud.githubusercontent.com/assets/18153674/23336207/3e29714c-fb97-11e6-81aa-79ce51d87661.png)

I am connected to localhost xd, I have the last version of it, my client does not show the names of the other players

Try it here: http://shairplus.tk/

Please login with A server Localhost /?ip=127.0.0.1:xxx

Because the servers in the list are not mine, and have another version lol xD

**Comment by Tucsky** [comment]
Same on nbk.io, cell.sh

**Comment by AlexHGaming** [comment]
This was all fixed in a recent pull request.
Reinstall your server then see if it works then.

**Comment by Tucsky** [comment]
@AlexHGaming still an issue on 1.6.0
![2017-02-26 11 49 48](https://cloud.githubusercontent.com/assets/5738336/23339062/420e024a-fc1a-11e6-9a1d-b614a5ae3f5e.gif)

**Comment by AlexHGaming** [comment]
What's it like on the vanilla client?

**Comment by AlexHGaming** [comment]
isn't everyone on your server got an unnamed cell?

**Comment by Tucsky** [comment]
only vanilla & astr.io display correct names on LB :/
![image](https://cloud.githubusercontent.com/assets/5738336/23339131/beab536a-fc1b-11e6-843d-924a562bf68a.png)

**Comment by Tucsky** [comment]
Same for old.ogarul,ogar.mivabe.nl and every cigar based client apparently

![image](https://cloud.githubusercontent.com/assets/5738336/23339203/8762564a-fc1d-11e6-9163-3beb9978df1a.png)

**Comment by AlexHGaming** [comment]
We only fix things on the vanilla client, not others.

**Comment by Tucsky** [comment]
@AlexHGaming Why

**Comment by Jhair2015** [comment]
lol

**Comment by MastaCoder** [comment]
@Tucsky because there isn't a reason to fix the other ones..?

**Comment by Megabyte918** [comment]
Fixed in latest version of PlayerTracker.js

**Comment by Jhair2015** [comment]
@Megabyte918 Thanks!
